---
- name: Setup nginx in docker and display image
  hosts: all_workers
  become: yes

  vars:
    image_src: /home/engineer/06.Ansible/webserver/images/test.png
    image_dest: /var/pic/test.png
    nginx_conf: /tmp/nginx.conf

  tasks:
    - name: Create directory for the image
      ansible.builtin.file:
        path: /var/pic
        state: directory
        mode: '0755'

    - name: Copy the image to the remote server
      ansible.builtin.copy:
        src: "{{ image_src }}"
        dest: "{{ image_dest }}"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Install docker
      ansible.builtin.package:
        name: docker.io
        state: present
        update_cache: yes

    - name: Check docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove default nginx configuration if it exists
      ansible.builtin.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf"
        detach: true
      ignore_errors: yes

    - name: Create the nginx configuration file
      ansible.builtin.copy:
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;
              log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';
              access_log /var/log/nginx/access.log main;
              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;

              server {
                  listen 80;
                  server_name _;

                  location / {

                      return 301 /test.png;
                  }

                  location /test.png {
                      alias /var/pic/test.png;
                  }
              }
          }
        dest: "{{ nginx_conf }}"
        owner: root
        group: root
        mode: '0644'


    - name: Run nginx in a docker container with custom configuration
      ansible.builtin.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - "{{ nginx_conf }}:/etc/nginx/nginx.conf"
          - "{{ image_dest }}:/var/pic/test.png"
        restart_policy: always